### ISSUE TITLE
problems exporting PSM reports

### ISSUE THREAD

**Issue by jcanderan** [compomics/reporter#15]
Hello,

I can successfully export Peptide/Protein reports (both in windows and linux), but cannot export any form of a PSM report regardless of the psdb used.

Here's a sample error log from trying in Windows GUI:

```
java.lang.NullPointerException: Cannot read the array length because "keys" is null
	at eu.isas.reporter.export.report.sections.ReporterPsmSection.writeSection(ReporterPsmSection.java:188)
	at eu.isas.reporter.export.report.ReporterExportFactory.writeExport(ReporterExportFactory.java:482)
	at eu.isas.reporter.gui.export.ReportDialog$11.run(ReportDialog.java:447)
```

Here's a sample error log from trying in linux command-line with a different psdb:

```
java.lang.NullPointerException
        at eu.isas.reporter.export.report.sections.ReporterPsmSection.writeSection(ReporterPsmSection.java:188)
        at eu.isas.reporter.export.report.ReporterExportFactory.writeExport(ReporterExportFactory.java:482)
        at eu.isas.reporter.cli.CLIExportMethods.exportReport(CLIExportMethods.java:91)
        at eu.isas.reporter.cli.ReporterCLI.call(ReporterCLI.java:581)
        at eu.isas.reporter.cli.ReporterCLI.main(ReporterCLI.java:845)
```

Thanks!

**Comment by hbarsnes** [comment]
Thanks for letting us know! This has now been fixed and a new version will be released soon.

**Comment by hbarsnes** [comment]
I've just released a new version of Reporter that should solve this issue. If you still have issues with the PSM reports, please let me know and I'll reopen the issue.

**Comment by jcanderan** [comment]
Thanks for working on this!

It gets further than it did but now a new error when exporting report type 4 pops up:

```
java.lang.IllegalArgumentException: No best match found for spectrum -3083128518393361966.
        at eu.isas.reporter.export.report.sections.ReporterPsmSection.writeSection(ReporterPsmSection.java:275)
        at eu.isas.reporter.export.report.ReporterExportFactory.writeExport(ReporterExportFactory.java:482)
        at eu.isas.reporter.cli.CLIExportMethods.exportReport(CLIExportMethods.java:91)
        at eu.isas.reporter.cli.ReporterCLI.call(ReporterCLI.java:581)
        at eu.isas.reporter.cli.ReporterCLI.main(ReporterCLI.java:845)
```

Here's the error for a different file:

```
java.lang.IllegalArgumentException: No best match found for spectrum -5146861328799035303.
        at eu.isas.reporter.export.report.sections.ReporterPsmSection.writeSection(ReporterPsmSection.java:275)
        at eu.isas.reporter.export.report.ReporterExportFactory.writeExport(ReporterExportFactory.java:482)
        at eu.isas.reporter.cli.CLIExportMethods.exportReport(CLIExportMethods.java:91)
        at eu.isas.reporter.cli.ReporterCLI.call(ReporterCLI.java:581)
        at eu.isas.reporter.cli.ReporterCLI.main(ReporterCLI.java:845)
```

**Comment by hbarsnes** [comment]
I've just released a new version of Reporter attempting to fix the issue. Please give it a go and let me know if it solves the problem?

**Comment by jcanderan** [comment]
Fixed the issue for the files I've tested.

Thanks!
