### ISSUE TITLE
How to set the labelling method (TMT10/11, iTRAQ, ...) on command line

### ISSUE THREAD

**Issue by steve-lefever** [compomics/reporter#23]
Hi,

Can the labelling method be set when running Reporter command line? If so, how is this done? I can't find that info when using either PathSettingsCLI or ReporterCLI

Kind regards,
Steve

**Comment by steve-lefever** [comment]
Hi,

You can close the issue, I found that you can use -method for this while using eu.isas.reporter.cli.ReporterCLI. Don't know why I missed it.

Kind regards,
Steve

**Comment by hbarsnes** [comment]
Hi Steve,

You can find all of the ReportCLI command line options here: https://github.com/compomics/reporter/blob/master/src/main/java/eu/isas/reporter/cli/ReporterCLIParameters.java

I assume that `methods` is the one you are interested in.

Best regards,
Harald

**Comment by hbarsnes** [comment]
>You can close the issue, I found that you can use -method for this while using eu.isas.reporter.cli.ReporterCLI. Don't know why I missed it.

I think we posted at the same time. :)

**Comment by steve-lefever** [comment]
Hi Harald,

I'm now getting this error message:

```
root@b7d984e774e8:/var/tmp/test/samples/19CPTAC_HNSCC_Proteome_JHU_20191003# java -Xmx250G -Xms250G -XX:MaxMetaspaceSize=250G -cp /var/tmp/Reporter-0.10.4/Reporter-0.10.4.jar eu.isas.reporter.cl
i.ReporterCLI -method TMT11 -id /var/tmp/test/samples/19CPTAC_HNSCC_Proteome_JHU_20191003/19CPTAC_HNSCC_Proteome_JHU_20191003.psdb -out /var/tmp/test/samples/19CPTAC_HNSCC_Proteome_JHU_20191003/19CPTAC_HNSCC_Proteome_JHU_20191003_reporter.psdb -temp_folder /var/tmp/test/temp/
Path configuration completed.
Fri Oct 06 12:54:25 GMT 2023 Opening PeptideShaker Project. Please Wait...
Fri Oct 06 12:54:26 GMT 2023 An error occurred while reading:
/var/tmp/test/samples/19CPTAC_HNSCC_Proteome_JHU_20191003/19CPTAC_HNSCC_Proteome_JHU_20191003.psdb.

Please verify that the Reporter version used to create
the file is compatible with your version of Reporter.
```

The .psdb file was created using PeptideShaker v2.2.25, and no error message popped up when running PeptideShaker.

Kind regards,
Steve

**Comment by hbarsnes** [comment]
Hi Steve,

The PeptideShaker-Report compatibility is a bit complicated. Basically, you have to make sure that you are using versions that have the same backend code. However, PeptideShaker v2.2.25 should be compatible with Reporter 0.10.4 (according to the [release notes](https://github.com/compomics/reporter/wiki/ReleaseNotes)).

Are there any errors in the Report log file?

Best regards,
Harald

**Comment by steve-lefever** [comment]
Hi Harald,

Where's the log located?

Kind regards,
Steve

**Comment by hbarsnes** [comment]
Hi Steve,

> Where's the log located?

It should be in the Reporter-X.Y.Z\resources folder.

Best regard,
Harald

**Comment by steve-lefever** [comment]
Hi Harald,

The log file is stating this:

```
Fri Oct 06 13:59:47 GMT 2023: Reporter version 0.10.4.
Memory given to the Java virtual machine: 268435456000 b.
Total amount of memory in the Java virtual machine: 268435456000 b.
Free memory: 268368347136 b.
Java version: 11.0.20.1.
org.apache.commons.cli.MissingArgumentException: Missing argument for option: method
        at org.apache.commons.cli.DefaultParser.checkRequiredArgs(DefaultParser.java:231)
        at org.apache.commons.cli.DefaultParser.handleOption(DefaultParser.java:394)
        at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:474)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:542)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:712)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:679)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:660)
        at eu.isas.reporter.cli.ReporterCLI.main(ReporterCLI.java:1144)
```

I've checked and the variable supplied to the -method argument was indeed empty.

Kind regards,
Steve

**Comment by steve-lefever** [comment]
Hi Harald,

I'm now receiving this error message:

`Fri Oct 06 14:06:49 GMT 2023 The reporter quantification methods to use could not be inferred, please specify a method from the isotopic correction file as command line parameter.`

Reporter is apparently not using the default values for this. Do you have a template for the .xml file that needs to be supplied as part of the -isotopes argument?

Kind regards,
Steve

**Comment by steve-lefever** [comment]
Hi Harald,

Could it be that Reporter isn't recognizing the value I've supplied for the -method argument, which results in the error message above? I'm currently using `-method TMT11`. What are the allowed values for the -method argument?

Kind regards,
Steve

**Comment by hbarsnes** [comment]
Hi Steve,

The default methods xml file is found in "Reporter-X.Y.Z\resources\conf\defaultMethods.xml" where you will also find the names of the supported methods. The one you are looking for seems to be "TMT 11-plex".

Best regards,
Harald

**Comment by steve-lefever** [comment]
Hi Harald,

I'm still having problems generating both the PeptideShaker and Reporter reports. I also noticed that the psdb files generated by PeptideShaker and Reporter have exactly the same size, is that possible?

While generating the report PeptideShaker gives me this error message:

```
Path configuration completed.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Thu Oct 12 09:45:51 GMT 2023 Exporting. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90%#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ed100582e17, pid=843, tid=844
#
# JRE version: OpenJDK Runtime Environment (11.0.20.1+1) (build 11.0.20.1+1-post-Ubuntu-0ubuntu120.04)
# Java VM: OpenJDK 64-Bit Server VM (11.0.20.1+1-post-Ubuntu-0ubuntu120.04, mixed mode, tiered, g1 gc, linux-amd64)
# Problematic frame:
# C  [sqlite-3.40.0.0-b4776a81-2617-4d82-a4e0-9b0c1540a693-libsqlitejdbc.so+0x11e17]
#
# Core dump will be written. Default location: /workdir/core.843
#
# An error report file with more information is saved as:
# /workdir/hs_err_pid843.log
#
# If you would like to submit a bug report, please visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-lts
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
/usr/bin/bash: line 16:   843 Aborted                 (core dumped) java -Xmx250G -Xms50G -XX:MaxMetaspaceSize=250G -cp PeptideShaker-2.2.25/PeptideShaker-2.2.25.jar eu.isas.peptideshaker.cmd.ReportCLI -in bam2fastq/cloud_run/samples/19CPTAC_HNSCC_Proteome_JHU_20191003/19CPTAC_HNSCC_Proteome_JHU_20191003.psdb -out_reports /workdir/ -report_prefix PS_ -reports 6 -temp_folder /workdir/temp/ -use_log_folder 0
[Thu Oct 12 10:54:23 2023]
```

And Reporter gives me this message :

```
Please verify that the Reporter version used to create
the file is compatible with your version of Reporter.
```

With this in `resources/Reporter.log`

```
Thu Oct 12 11:00:13 GMT 2023: Reporter version 0.10.4.
Memory given to the Java virtual machine: 268435456000 b.
Total amount of memory in the Java virtual machine: 53687091200 b.
Free memory: 53636757504 b.
Java version: 11.0.20.1.
java.io.IOException: FASTA file not found /workdir/homo_sapiens_GRCh38.uniprot_smorfeome.fasta.
        at eu.isas.peptideshaker.utils.PsdbParent.loadPsdbFile(PsdbParent.java:299)
        at eu.isas.reporter.io.ProjectImporter.importPeptideShakerProject(ProjectImporter.java:125)
        at eu.isas.reporter.cli.ReportCLI.call(ReportCLI.java:137)
        at eu.isas.reporter.cli.ReportCLI.main(ReportCLI.java:449)
```

Is it possible that something is wrong with the initial psdb file generated by PeptideShaker, although it doesn't crash or generate an error when it runs and creates the file?

I'm running SearchGUI-4.3.1, PeptideShaker 2.2.25 and Reporter 0.10.4

Kind regards,
Steve

**Comment by hbarsnes** [comment]
Hi Steve,

I would recommend updating to SearchGUI v4.3.1, PeptideShaker v3.0.1 and Reporter v0.12.0 to see if that helps.

I think I would also recommend updating to a more recent version of OpenJDK.

As for the Reporter exception, can you show me the command line you are using? And does the given FASTA file exist?

Best regards,
Harald

**Comment by steve-lefever** [comment]
Hi Harald,

Can you tell me what files must be present in the input folder when running the specific tools? For example when running Reporter to generate the report it seems that the fasta file must be available, however this is nowhere specified for any of the tools in the available documentation, nor can it be determined from the command line arguments associated with each of the tools.

Kind regards,
Steve

**Comment by hbarsnes** [comment]
Hi Steve,

> Can you tell me what files must be present in the input folder when running the specific tools?

If you use a PeptideShaker psdb file as input to Reporter the spectrum and FASTA files have to either be available at the locations used when generating the PeptideShaker project or located in the same folder as the psdb file. You can get around this by exporting the PeptideShaker project as a zip file and using this as input to Reporter.

A similar trick can be used for PeptideShaker where the https://github.com/compomics/searchgui/wiki/SearchCLI#optional-output-compression-parameters options can be used to include the spectrum and FASTA files in the SearchGUI output.

Best regards,
Harald
